# Generated by Django 4.0.4 on 2022-04-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_blog_time_alter_comment_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='time',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='blog',
            name='last_updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='last_updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
