# Generated by Django 4.0.3 on 2022-04-14 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
